services:
  api:
    build: .
    container_name: go-api
    ports:
      - "3009:3009"
    working_dir: /app
    environment:
      - ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=dzfinance
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: go-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dzfinance
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: